services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ".:/var/nest-shop-server"
    env_file:
      - ./.env

  db:
    container_name: db
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_DB: my_shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: AndySatu989!e
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    ports:
      - 54322:5432

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3000:80"
    depends_on:
      - api