services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ".:/var/nest-shop-server"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=AndySatu989!e
      - POSTGRES_DATABASE=my_shop
      - CHECKOUT_URL=http://localhost:4000
      - JWT_SECRET=444444
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=465
      - SMTP_SECURE=true
      - SMTP_USERNAME=andyrhmann@gmail.com
      - SMTP_PASSWORD=ifpfazghxoawzrqg
      - GOOGLE_CLIENT=170095590590-i2p45vs96q11admvl2b6pbgbsc298dmd.apps.googleusercontent.com
      - FACEBOOK_APP_ID=2659171481015709
      - FACEBOOK_CLIENT_SECRET=71602baa5187a698d0e96c8e069aab3d
      - STRIPE_API_KEY=sk_test_51HV6JZKUntXL20P7LmuoxTx7yINSt5ZBopBwhF7AOBQuUyXRQSL4jLBtAVS28NNBpOyMfZuNnFNMViuooKVlczEV00mNMfW5Sy

  db:
    container_name: db
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_DB: my_shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: AndySatu989!e
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    ports:
      - 54322:5432

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3000:80"
    depends_on:
      - api